name: Deploy Django + Celery + Flower to EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECR_REPOSITORY_CELERY: ${{ secrets.ECR_REPOSITORY_CELERY }}
  ECR_REPOSITORY_FLOWER: ${{ secrets.ECR_REPOSITORY_FLOWER }}
  IMAGE_TAG: latest

  # PostgreSQL
  POSTGRESQL_DATABASE_NAME: ${{ secrets.POSTGRESQL_DATABASE_NAME }}
  POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_USERNAME }}
  POSTGRESQL_SERVER_NAME: ${{ secrets.POSTGRESQL_SERVER_NAME }}
  POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
  PORT: 5432

  # OpenAI and Deepgram API Keys
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  DEEPGRAM_API_KEY: ${{ secrets.DEEPGRAM_API_KEY }}

  # AWS SES Config
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_PORT: 587
  EMAIL_USE_TLS: true
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}

  # AWS S3 Config
  USE_S3: true
  AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
  AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Intuit Config
  INTUIT_VERIFIER_TOKEN: ${{ secrets.INTUIT_VERIFIER_TOKEN }}
  INTUIT_CLIENT_ID: ${{ secrets.INTUIT_CLIENT_ID }}
  INTUIT_CLIENT_SECRET: ${{ secrets.INTUIT_CLIENT_SECRET }}
  NEW_INTUIT_REDIRECT_URI: ${{ secrets.NEW_INTUIT_REDIRECT_URI }}
  INTUIT_ENVIRONMENT: ${{ secrets.INTUIT_ENVIRONMENT }}

  # Stripe Config
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}

  # Redis URL
  REDIS_URL: ${{ secrets.REDIS_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

    # - name: Run Tests
    #   run: |
    #     python myapp/manage.py test

  # package:
  #   runs-on: ubuntu-latest
  #   needs: [build]  # ðŸ‘ˆ needs to package if build is successful

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}

  #     - name: Log in to Amazon ECR
  #       uses: aws-actions/amazon-ecr-login@v2

  #     - name: Build and Tag Docker Images
  #       run: |
  #         docker build -t engagex-stream-app -f Dockerfile .
  #         docker tag engagex-stream-app $ECR_REPOSITORY:$IMAGE_TAG

  #     - name: Push Docker Images to ECR
  #       run: |
  #         docker push $ECR_REPOSITORY:$IMAGE_TAG

  # deploy:
  #     runs-on: ubuntu-latest
  #     needs: [package]  # ðŸ‘ˆ This ensures `package` completes before `deploy` starts

  #     steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Set Up SSH Key
  #       shell: bash
  #       run: |
  #         echo "${{ secrets.EC2_SSH_KEY }}" > ~/ec2-user-ssh.pem
  #         chmod 400 ~/ec2-user-ssh.pem

  #     - name: Deploy Code
  #       shell: bash
  #       run: |
  #         # SSH into the EC2 instance and deploy
  #         ssh -o StrictHostKeyChecking=no -i ~/ec2-user-ssh.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
  #         cd /home/${{ secrets.EC2_USER }}/app/
  #         aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
  #         docker-compose pull
  #         docker-compose up -d --remove-orphans
  #         docker system prune -a -f # remove unused images, containers, volumes, and networks
  #         EOF
  #         echo "Deployment completed!"